"""The manuscript's tables, from the records on the Hub (`notebooks/manuscript_tables`).

Each method returns the table as it is displayed and writes its LaTeX body — a `tabular`, booktabs rules, no float
and no caption — to `<out>/<name>.tex`, for the manuscript to `\\input`. Every number comes from a record a notebook
wrote: `main_<corpus>.json` (Tables 1, 3 and 6, the routing behaviour), `exploration_hit_asr.json` and
`pool_size.json` (the ablation), `timing_<corpus>.json` (the cost) and `synthetic.json`.
"""

__all__ = ['ManuscriptTables', 'default_table_dir']

from pathlib import Path

import numpy as np
import pandas as pd

from hitasr.configs import ABLATION, ARMS, CORPUS_TITLES, MAIN, SPACES, TIMING
from hitasr.experiment import LABELS
from labkit.pretty import Table
from labkit.significance import TEST_NOTE

SYSTEM_ROWS = (("bsm", "reference"), ("random", "reference"), ("rover_conf", "fusion"), ("cn_mbr", "fusion"),
               ("mlp_pool", "pooled"), ("adastt_ce", "pooled"), ("hit_asr", "ours"),
               ("oracle", "oracle"), ("oracle_tol1", "oracle"), ("oracle_tol2", "oracle"))
TESTED = ("bsm", "random", "rover_conf", "cn_mbr", "mlp_pool", "adastt_ce")
ROUTERS = ("mlp_pool", "adastt_ce", "hit_asr", "oracle")


def default_table_dir():
    """`tables/` at the repository root when run from its `notebooks/`, else `tables/` here."""
    here = Path.cwd()
    if here.name == "notebooks" and (here.parent / "pyproject.toml").exists():
        return here.parent / "tables"
    return here / "tables"


def _tex(s):
    return (str(s).replace("\\", r"\textbackslash{}").replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
            .replace("#", r"\#").replace("±", r"$\pm$").replace("—", "---").replace("–", "--")
            .replace("Δ", r"$\Delta$").replace("×", r"$\times$").replace("<", r"$<$").replace(">", r"$>$"))


def _pm(mean, sd, scale=100, digits=2):
    if mean is None or not np.isfinite(mean):
        return "—"
    return f"{scale * mean:.{digits}f} ± {scale * sd:.{digits}f}" if sd is not None and np.isfinite(sd) \
        else f"{scale * mean:.{digits}f}"


def _tabular(df, colspec=None, groups=None, bold=None, rules=()):
    """A frame of display strings as a booktabs `tabular`. `groups`: `[(title, n_columns)]` over the columns after the
    first; `bold`: a set of `(row, column)` cells; `rules`: row positions a `\\midrule` precedes."""
    colspec = colspec or "l" + "r" * (df.shape[1] - 1)
    lines = [r"\begin{tabular}{%s}" % colspec, r"\toprule"]
    if groups:
        heads, rule, col = [""], [], 2
        for title, n in groups:
            heads.append(r"\multicolumn{%d}{c}{%s}" % (n, _tex(title)))
            rule.append(r"\cmidrule(lr){%d-%d}" % (col, col + n - 1))
            col += n
        lines += [" & ".join(heads) + r" \\", " ".join(rule)]
    lines.append(" & ".join(_tex(c.split("·")[-1].strip()) for c in df.columns) + r" \\")
    lines.append(r"\midrule")
    for i, (_, row) in enumerate(df.iterrows()):
        if i in rules:
            lines.append(r"\midrule")
        cells = [(r"\textbf{%s}" % _tex(v)) if bold and (i, c) in bold else _tex(v) for c, v in row.items()]
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


class ManuscriptTables:
    """Every table of the manuscript. `out` is where the `.tex` files go (default: `tables/` at the repository root)."""

    def __init__(self, out=None, corpora=tuple(MAIN)):
        from hitasr.records import load_record
        self.out = Path(out) if out is not None else default_table_dir()
        self.out.mkdir(parents=True, exist_ok=True)
        self.corpora = tuple(corpora)
        self.main = {c: load_record(f"main_{c}", c) for c in self.corpora}
        self.t3 = {c: {r["model"]: r for r in self.main[c]["tables"]["table3"]} for c in self.corpora}
        self._load = load_record
        print(f"read {len(self.main)} main records; the LaTeX goes to {self.out.name}/")

    def _write(self, name, text, note=None):
        header = f"% {note}\n" if note else ""
        (self.out / f"{name}.tex").write_text(f"% Generated by notebooks/manuscript_tables from the records; do not edit.\n"
                                              f"{header}{text}")
        return f"→ {self.out.name}/{name}.tex"

    # ---------------------------------------------------------------- Table 1 --

    def datasets(self):
        """The corpora, their expert trios and the partition every model uses."""
        stats = ("Total clips", "Hours", "Mean clip length (s)", "Reference words", "Hyperparameter hold-out",
                 "Evaluation rows (5x2)", "Train size (per fold)", "Test size (per fold)")
        rows = {"Experts": [", ".join(LABELS[m] for m in self.main[c]["members"]) for c in self.corpora]}
        for s in stats:
            vals = []
            for c in self.corpora:
                v = {r["statistic"]: r[c] for r in self.main[c]["tables"]["table1"]}[s]
                vals.append(f"{v:,.1f}" if isinstance(v, float) else f"{v:,}")
            rows[s] = vals
        rows["Best single expert WER (%)"] = [_pm(self.t3[c]["bsm"]["corpus_wer"], None) for c in self.corpora]
        rows["Oracle WER (%)"] = [_pm(self.t3[c]["oracle"]["corpus_wer"], None) for c in self.corpora]
        df = pd.DataFrame(rows, index=[CORPUS_TITLES[c] for c in self.corpora]).T.reset_index()
        df = df.rename(columns={"index": ""})
        where = self._write("datasets", _tabular(df, colspec="l" + "l" * len(self.corpora)))
        return Table(df, title="Table 1 — datasets", caption=where)

    # ---------------------------------------------------------------- Table 2 --

    def spaces(self):
        """The free hyperparameters of every arm and their choices (the same on every corpus)."""
        rows = []
        for arm in ARMS:
            for n, p in SPACES[arm].items():
                if p.frozen is None:
                    rows.append({"Model": LABELS[arm], "Parameter": n,
                                 "Choices": ", ".join(str(c) for c in p.choices)})
        df = pd.DataFrame(rows)
        first = df["Model"].ne(df["Model"].shift())
        tex = df.assign(Model=np.where(first, df["Model"], ""))
        where = self._write("spaces", _tabular(tex, colspec="lll",
                                               rules=[i for i in np.flatnonzero(first.to_numpy()) if i]))
        return Table(df, title="Table 2 — hyperparameter spaces", caption=where, group="Model", mono=("Choices",))

    # ---------------------------------------------------------------- Table 3 --

    def main_results(self):
        """Test corpus WER (%, mean ± sd over the ten folds), the share of the oracle gap closed (GC, %) and the selection
        accuracy (Acc, %), per corpus."""
        cols, bold = {}, set()
        for c in self.corpora:
            t = self.t3[c]
            best = min((k for k, f in SYSTEM_ROWS if f != "oracle"), key=lambda k: t[k]["corpus_wer"])
            cols[c] = best
        rows = []
        for i, (k, fam) in enumerate(SYSTEM_ROWS):
            row = {"System": LABELS[k]}
            for c in self.corpora:
                r = self.t3[c][k]
                row[f"{CORPUS_TITLES[c]} · WER"] = _pm(r["corpus_wer"], r["corpus_wer_sd"])
                row[f"{CORPUS_TITLES[c]} · GC"] = _pm(r["gap_closed_tol0"], None, digits=1)
                row[f"{CORPUS_TITLES[c]} · Acc"] = "—" if r.get("n_fused") else _pm(r["acc_tol0"], None, digits=1)
                if cols[c] == k:
                    bold.add((i, f"{CORPUS_TITLES[c]} · WER"))
            rows.append(row)
        df = pd.DataFrame(rows)
        fams = [f for _, f in SYSTEM_ROWS]
        rules = [i for i in range(1, len(fams)) if fams[i] != fams[i - 1]]
        where = self._write("main_results", _tabular(df, groups=[(CORPUS_TITLES[c], 3) for c in self.corpora],
                                                     bold=bold, rules=rules))
        show = df.assign(family=fams)
        return Table(show, title="Table 3 — main results", caption=f"WER (%) mean ± sd over ten folds; GC and Acc in %. "
                     f"{where}", group="family", highlight=lambda r: r["System"] == "HIT-ASR")

    # ---------------------------------------------------------------- Table 6 --

    def significance(self):
        """HIT-ASR against every system: ΔWER = WER(system) − WER(HIT-ASR) in WER points (positive: HIT-ASR better) and
        the p-value of the paper's test on the same folds."""
        rows = []
        for k in TESTED:
            row = {"System": LABELS[k]}
            for c in self.corpora:
                t6 = {r["comparator"]: r for r in self.main[c]["tables"]["table6"]["corpus_wer"]["rows"]}
                r = t6[k]
                row[f"{CORPUS_TITLES[c]} · ΔWER"] = f"{100 * r['effect']:+.2f}"
                row[f"{CORPUS_TITLES[c]} · p"] = "<0.001" if r["p"] < 0.001 else f"{r['p']:.3f}"
            rows.append(row)
        df = pd.DataFrame(rows)
        where = self._write("significance", _tabular(df, groups=[(CORPUS_TITLES[c], 2) for c in self.corpora]),
                            note=TEST_NOTE)
        return Table(df, title="Table 6 — HIT-ASR against every system (corpus WER)", caption=where, note=TEST_NOTE)

    # ------------------------------------------------------------------ routing --

    def routing(self):
        """How each router distributes the clips over its corpus's trio (%, experts E1–E3 in the order of Table 1),
        and its selection accuracy (%, mean ± sd over the folds)."""
        rows = []
        for c in self.corpora:
            members = self.main[c]["members"]
            for k in ROUTERS:
                r = self.t3[c][k]
                row = {"Corpus": CORPUS_TITLES[c], "Router": LABELS[k]}
                for i, m in enumerate(members, 1):
                    row[f"E{i}"] = f"{100 * r[f'share_{m}']:.1f}"
                row["Acc"] = _pm(r["acc_tol0"], r["acc_tol0_sd"], digits=1)
                rows.append(row)
        df = pd.DataFrame(rows)
        tex = df.assign(Corpus=np.where(df["Corpus"].ne(df["Corpus"].shift()), df["Corpus"], ""))
        trios = "; ".join(f"{CORPUS_TITLES[c]}: " + " / ".join(LABELS[m] for m in self.main[c]["members"])
                          for c in self.corpora)
        where = self._write("routing", _tabular(tex, colspec="ll" + "r" * (df.shape[1] - 2),
                                                rules=list(range(len(ROUTERS), len(df), len(ROUTERS)))),
                            note=f"E1-E3: {trios}")
        return Table(df, title="Routing behaviour", caption=f"E1–E3: {trios}. {where}", group="Corpus",
                     highlight=lambda r: r["Router"] == "HIT-ASR")

    # ----------------------------------------------------------------- ablation --

    def ablation(self):
        """HIT-ASR's design switches on the hold-out exploration, averaged over the corpora: the share of configurations
        that collapsed onto the best single expert, the median and best share of the oracle gap closed, and on how many
        corpora the main search selected the level."""
        from hitasr.ablation import SWITCHES, switch_table, trials_frame
        tabs = []
        for c in ABLATION.corpora:
            ex, main = self._load("exploration_hit_asr", c), self._load(f"main_{c}", c)
            chosen = {k: str(main["params"]["hit_asr"][k]) for k in SWITCHES}
            t = pd.concat([switch_table(trials_frame(ex), s, collapse=ABLATION.collapse) for s in SWITCHES])
            tabs.append(t.assign(chosen=(t["level"] == t["switch"].map(chosen)).astype(int)))
        a = (pd.concat(tabs).groupby(["switch", "level"], sort=False)
             .agg(collapsed=("collapsed", "mean"), gap_median=("gap_median", "mean"), gap_best=("gap_best", "mean"),
                  chosen=("chosen", "sum")).reset_index())
        df = pd.DataFrame({"Switch": a["switch"], "Level": a["level"],
                           "Collapsed (%)": (100 * a["collapsed"]).map("{:.0f}".format),
                           "GC median (%)": (100 * a["gap_median"]).map("{:.1f}".format),
                           "GC best (%)": (100 * a["gap_best"]).map("{:.1f}".format),
                           "Selected": a["chosen"].map(lambda n: f"{n}/{len(ABLATION.corpora)}")})
        tex = df.assign(Switch=np.where(df["Switch"].ne(df["Switch"].shift()), df["Switch"], ""))
        where = self._write("ablation", _tabular(tex, colspec="llrrrr",
                                                 rules=[i for i in np.flatnonzero(df["Switch"].ne(df["Switch"].shift())
                                                                                  .to_numpy()) if i]))
        return Table(df, title="Ablation — HIT-ASR's switches on the hold-out", caption=where, group="Switch")

    def pool_size(self):
        """HIT-ASR and MLP-pool on K real experts, on the hold-out: share of the oracle gap closed (%, mean ± sd over
        the seeds), WER (%) and selection accuracy (%)."""
        from hitasr.ablation import pool_table
        rows = []
        for c in ABLATION.k_corpora:
            t = pool_table(self._load("pool_size", c), LABELS)
            for _, r in t.iterrows():
                rows.append({"Corpus": CORPUS_TITLES[c], "K": int(r["K"]), "Router": r["arm"],
                             "GC": _pm(r["gap_closed"], r["gap_sd"], digits=1),
                             "WER": _pm(r["corpus_wer"], None), "Acc": _pm(r["acc"], None, digits=1)})
        df = pd.DataFrame(rows)
        where = self._write("pool_size", _tabular(df, colspec="lrlrrr"))
        return Table(df, title="Pool size — K experts on the hold-out", caption=where, group="Corpus")

    # --------------------------------------------------------------------- cost --

    def cost(self):
        """Per corpus, ms per clip on raw audio at batch 1: every encoder, the router and one decoder (HIT-ASR) against
        the best single expert and decode-all + ROVER."""
        from hitasr.timing import Timing
        s = Timing(TIMING, level=1).summary().df.set_index("corpus")
        rows = []
        for c in [c for c in self.corpora if c in s.index]:
            r = s.loc[c]
            rows.append({"Corpus": CORPUS_TITLES[c], "Encoders": f"{r['encoders_ms']:.1f}",
                         "Router": f"{r['router_ms']:.1f}", "Decoder": f"{r['decoder_ms']:.1f}",
                         "HIT-ASR": f"{r['hit_ms']:.1f}", "Best single": f"{r['best_single_ms']:.1f}",
                         "Decode all": f"{r['decode_all_ms']:.1f}", "× best single": f"{r['x_best_single']:.2f}",
                         "Saved vs decode all (%)": f"{100 * r['saved_vs_all']:.0f}"})
        df = pd.DataFrame(rows)
        where = self._write("cost", _tabular(df))
        return Table(df, title="Cost — ms per clip on raw audio, batch 1", caption=where)

    # ---------------------------------------------------------------- synthetic --

    def synthetic(self):
        """The synthetic regime switch: WER (%) and selection accuracy (%), mean ± sd over the seeds, and the share of
        the gap closed (%), per number of experts K."""
        rec = self._load("synthetic")
        r = pd.DataFrame(rec["results"])
        names = {"random": "Random", "bsm": "Best single expert", "mlp_pool": "MLP-pool", "hit_asr": "HIT-ASR",
                 "oracle": "Oracle"}
        rows = []
        for K in sorted(r["K"].unique()):
            for arm in names:
                x = r[(r["K"] == K) & (r["arm"] == arm)]
                rows.append({"K": int(K), "Method": names[arm], "WER": _pm(x["wer"].mean(), x["wer"].std()),
                             "Acc": _pm(x["sel_acc"].mean(), x["sel_acc"].std(), digits=1),
                             "GC": _pm(x["gap_closed"].mean(), None, digits=1)})
        df = pd.DataFrame(rows)
        where = self._write("synthetic", _tabular(df, colspec="rlrrr",
                                                  rules=list(range(len(names), len(df), len(names)))))
        return Table(df, title="Synthetic regime switch", caption=where, group="K",
                     highlight=lambda row: row["Method"] == "HIT-ASR")

    # ------------------------------------------------------------------ experts --

    def experts(self):
        """The experts of the study: checkpoint, encoder width d and frame rate, and the corpora whose trio holds it."""
        used = {}
        for c in self.corpora:
            for m in self.main[c]["members"]:
                used.setdefault(m, []).append(c)
        rows = []
        for m, cs in used.items():
            mf = self._load(f"extract_{m}", cs[0])["manifest"]
            rows.append({"Expert": LABELS[m], "Checkpoint": mf["model_id"], "d": str(mf["d"]),
                         "Hz": f"{mf['frame_rate_hz']:.1f}", "Corpora": ", ".join(CORPUS_TITLES[x] for x in cs)})
        df = pd.DataFrame(rows)
        where = self._write("experts", _tabular(df, colspec="llrrl"))
        return Table(df, title="The experts", caption=where, mono=("Checkpoint",))

    def all(self):
        """Every table, in the manuscript's order."""
        return [self.datasets(), self.spaces(), self.main_results(), self.significance(), self.routing(),
                self.ablation(), self.pool_size(), self.cost(), self.synthetic(), self.experts()]
